### ISSUE TITLE
Special character

### ISSUE THREAD

**Issue by nagualcode** [chinasaur/poptart#5]
Hello, it does not display special characters like ã é ô. Could it be the vera.ttf ?

**Comment by chinasaur** [comment]
My guess is this depends on the font file that is available. I'm just using the default that was provided in the old Raspi text rendering examples. Not sure when I'll be able to look into this further, but I'll keep it in mind.

**Comment by nagualcode** [comment]
Would you accept any financial incentive to complete this?
